version: "3.6"
services:
  # db:
  #   image: mysql:5.7
  #   container_name: my_db_app_david
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=david_data
  #   ports:
  #     - '3307:3306'
  # adminer:
  #   image: adminer
  #   # restart: always
  #   ports:
  #     - 8080:8080
    app:
      build:
        context: .
      ports:
        - 4000:4000
      volumes:
        - ./:/usr/src/app
        - node_modules:/usr/src/app/node_modules
volumes:
  node_modules: